### ISSUE TITLE
🐛 [BUG] 🐛 no instructions to setup callbackurl or domain

### ISSUE THREAD

**Issue by astroash** [mineshmshah/passport-tutorial#19]
You need to add your domain and callbackUrl on fb dev settings:
- domain is added on settings > `+ add platform`> choose website > eg http://localhost:5000
- add callbackUrl on Facebook login > settings > set `Valid OAuth redirect URIs` to `http://localhost:5000/auth/facebook/callback`

**Comment by Dragomirc** [comment]
domain is added on settings > + add platform> choose website > eg http://localhost:5000
add callbackUrl on Facebook login > settings >Valid OAuth redirect URIs > http://localhost:5000/auth/facebook/callback
