### ISSUE TITLE
Typos in Readme

### ISSUE THREAD

**Issue by astroash** [mineshmshah/passport-tutorial#3]
Here's a list of typo's with the errors in bold 😃 

>**Passort** uses 'strategies'..

> - Please make sure you **hav** a database

> The config.env file is not included that private Facebook info.

(grammatical)

>1. The npm install **wouldhave**

>includes the steps done **be** Facebook

**Comment by eliasmalik** [comment]
Some more typos:
> intgrated

> The config.env file is not included that private Facebook info

> implement some form authentification flow

> **we** _(We)_ are going to use the facebook OAuth flow

> **outside** _(out)_ of the box

> Add a secrete string

> streatetgy

> now at a place **that** _(where)_ we

> We shall have four routes that outlined below

> Now add the routes to after the imports

> Additional data **as** _(is)_ an object

> When we are out of the **google** _(OAuth flow)_ flow and...

> unnder

> borwser

> mehod

> We will **not** _(now)_ make use of the cookie-sessions module

> THe cookie needs two pieces of info

**Comment by mineshmshah** [comment]
All changed plus some more

**Comment by astroash** [comment]
Thanks lovely <3
